map_frame: map
coverage_frame: robot_0/base_footprint

# Rate at which progress tracker should be run
rate: 5.0  # 5 Hz

grid:
  width: 10.0
  height: 10.0
  resolution: 0.05
  origin:
    x: -5.0
    y: -5.0

coverage:
  # NOTE: To compensate for discretization, radius will be incremented further by 2*resolution
  # internally. Specify the radius accordingly.
  radius: 0.07
  # How effective cleaning in each timestep is
  effectivity: 0.75
