authors: []
blacklist: []
build_space: /home/ashwin/catkin_ws/build/release
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: /home/ashwin/catkin_ws/devel/release
extend_path: null
extends: null
install: false
install_space: install
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: /home/ashwin/catkin_ws/logs/release
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
